apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-django-capstone
spec:
  selector:
    matchLabels:
      app: react-django-capstone
  replicas: 2
  template:
    metadata:
      labels:
        app: react-django-capstone
    spec:
      containers:
        - name: backend
          image: akumar46/dockermages:vet_assit-backend
          ports:
            - containerPort: 8000
        - name: frontend
          image: akumar46/dockermages:vet_assit-frontend
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-service-capstone
  labels:
    name: react-service-capstone
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: django-service-capstone
  labels:
    name: django-service-capstone
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 32000