# Generated by Django 4.2.10 on 2024-03-09 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_alter_appointment_apmt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doc_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='pet_kind',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
