# Generated by Django 4.2.10 on 2024-03-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0004_appointment_doc_name_appointment_pet_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doc_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet_owner_id',
            field=models.IntegerField(),
        ),
    ]
