# Generated by Django 4.2.10 on 2024-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0005_alter_appointment_doc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='pet_id',
            field=models.IntegerField(),
        ),
    ]
